### ISSUE TITLE
input stream should be reset on completion or error

### ISSUE THREAD

**Issue by smart40** [drewnoakes/metadata-extractor#108]
When reading from an input stream, the input stream should be reset before readMetadata returns or an exception is thrown. 

This would allow alternative action to be taken by a client, e.g. loading the full jpeg image if there is no thumbnail.

**Comment by drewnoakes** [comment]
Why can't you call reset yourself? I'm not certain reset is supported on
all InputStream implementations.

**Comment by smart40** [comment]
Hi,

reset is not supported in basic InputStream but as I am passing a 
BufferedInputStream...

I can call setMark before calling ImageMetadataReader.readMetdata(is) 
but the detection
logic calls setMark(16) overriding anything I may have set first and 
then goes on to read
more than 16 bytes thus invalidating the marked position and making it 
impossible
to reset the stream back to the start (calling reset will throw an 
exception).

Interestingly if I call JpegMetadataReader directly then setMark is not 
called and all is ok.

I can work around this with a specialized BufferedInputStream but it 
would be better
if your library did not read beyond the readlimit in setMark.

best regards,

Peter

**Comment by Odrahcyr** [comment]
It is not possible to read the marklimit for an buffered input stream since the field is protected. I also see no reason why the library should accept an user set read limit. You should use a specialized stream and not depend on the implementation of readMetadata().

**Comment by smart40** [comment]
>It is not possible to read the marklimit for an buffered input stream 
since the field is protected
I don't see the relevance.
 > I also see no reason why the library should accept an user set read 
limit.
I am not saying that it should, but what it should not do is invalidate 
an input stream
or otherwise trash data that the client passes to it. It should be clear 
why this is bad,
for one problem see my original post.
 >You should use a specialized stream and not depend on the 
implementation of readMetadata()
No, an implementation should not force clients to make workarounds 
because of bad behaviour.

I believe the problem is in the first line of 
ImageMetadataReader.readMetadata.

If the client passes in a BufferedInputStream the implementation grabs 
it and uses it as it
sees fit and in doing so invalidates any marked position. If the 
implementation wants to use
a BufferedInputStream then it should allocate and use it's own, then it 
do whatever
it wants it with it.

BufferedInputStream  bufferedInputStream = inputStreaminstanceofBufferedInputStream
     ? (BufferedInputStream)inputStream
     :newBufferedInputStream(inputStream);

so replace with

BufferedInputStream  bufferedInputStream =newBufferedInputStream(inputStream);

if you really must use the clients BufferedInputStream then do not 
invalidate it.

**Comment by Odrahcyr** [comment]
>so replace with
>BufferedInputStream  bufferedInputStream =newBufferedInputStream(inputStream);

The reset would still fail because the read would occur on the original stream. You can either pass a deep copy of your stream to the library, open a second stream or use a specific class to solve this issue. If you pass a InputStream to a 3rd party library you should just close it after the method returns and use a independent InputStream for other things you might want to do in most cases. This is as far as I know common sense in Java.

```
	/**
	 * Reads metadata from an {@link InputStream}.
	 *
	 * @param inputStream
	 *            a stream from which the file data may be read. The stream must be positioned at the
	 *            beginning of the file's data.
	 * @return a populated {@link Metadata} object containing directories of tags with values and any processing errors.
	 * @throws ImageProcessingException
	 *             if the file type is unknown, or for general processing errors.
	 */
	@NotNull
	public static Metadata readMetadata(@NotNull final InputStream inputStream) throws ImageProcessingException, IOException 
```
This is the shortened doc + interface of readMetadata() There is no guarantee what happens to the InputStream and it doesn't say that it uses an independent stream. Using a independent stream inside the library would just be a huge waste of resources.

**Comment by black-snow** [comment]
The question we should ask is: When does a user make a call to *readMetadata()* w/ *InputStream* instead of *File*? In my case I'd always use the version w/ *File* except the case when I already have an open InputStream that I already used somewhere else or gonna need soon. Thus, I'd expect the same behaviour when passing *InputStream* then when passing *File* - the *File* won't be changed, does it? So imho *InputStream* shouldn't be "touched", neither.

**Comment by Odrahcyr** [comment]
The behavior is the same. If you pass a file it will read the file (with a file stream) and if you pass a input stream it will read the input stream. The only purpose of the stream is to extract metadata and nothing else. The readMetadata() for File objects is just a convenience method, so a user does not have to open and close a stream.

**Comment by drewnoakes** [comment]
@smart40 could you put a PR together with a unit test that shows the implementation you're proposing?

**Comment by drewnoakes** [comment]
I don't see any action to be taken here, so I'm closing this. Will re-open if someone produces a PR containing a valid failing unit test and sensible fix.
