### ISSUE TITLE
JpegProcessingException: Expected JPEG segment start identifier 0xFF, not 0x0

### ISSUE THREAD

**Issue by rmuller** [drewnoakes/metadata-extractor#121]
Expected JPEG segment start identifier 0xFF, not 0x0
com.drew.imaging.jpeg.JpegProcessingException
	at com.drew.imaging.jpeg.JpegSegmentReader.readSegments(JpegSegmentReader.java:118)
	at com.drew.imaging.jpeg.JpegMetadataReader.process(JpegMetadataReader.java:116)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:69)
	at com.drew.imaging.jpeg.JpegMetadataReader.readMetadata(JpegMetadataReader.java:76)
	at eu.infomas.dam.MetadataWrapper.readMetadata(MetadataWrapper.java:111)
	at eu.infomas.dam.SampleDataTest.testWithHeight(SampleDataTest.java:97)

I am able to process this file correctly with ImageMagick
![koker](https://cloud.githubusercontent.com/assets/754040/9444270/e9da09ee-4a85-11e5-9fe5-a09f26530205.jpeg)

(okay, i know this image is ugly. This is one of the corner cases :) )

**Comment by ArjohnKampman** [comment]
The reason that metadata-extractor fails to process this picture is that one of the segments specifies an incorect length. I have found a few pictures in the Enron data set that were affected by a similar issue: the specified segment length didn't include the two segment marker bytes. I'm not attaching these picture due to their very private nature, but I'm attaching a screen shot from a hex viewer instead:
![incorrect segment length](https://cloud.githubusercontent.com/assets/15195853/10841182/6716b35e-7ee7-11e5-80aa-84e59ccea40d.png)
As you can see, the first segment specifies 001A as the segment length, which would mean that the 2E00 (a '.' character and a null byte) at the second line would be the start of the second segment. Obviously, these two bytes should have been part of the first segment's data, with the second segment starting two bytes later.

I'll create a pull request for my fix which allows metadata-extractor to process both my problematic pictures as the one attached to this ticket properly. Please consider including this fix.

**Comment by drewnoakes** [comment]
Fixed via #129.
