### ISSUE TITLE
Use known file length when possible rather than reader.getLength which scans to EOF

### ISSUE THREAD

**Issue by mvmn** [drewnoakes/metadata-extractor#164]
Hi.

I've implemented a GUI utility that scans multiple files and shows stats for those files based on EXIF metadata, using your library.

It turned out to be very slow for TIFF, NEF and the likes.

After examining the code I've found out you have a little TODO mentioning that reader.getLength() calls should be avoided 'cause they force random access reader to read file completely, which is slow. And slow it is indeed. Since average NEF file I had was around 80Mb you can imagine how slow was scanning a couple of thousands of those

I've made a change in code to fix this in own fork. After the fix everything became blazingly fast in comparison.

Unfortunately I had a little time to fix things, so it's all quite raw, I don't have your Eclipse formatter (if you use Eclipse at all), many files had to be changed just to suite the change in API interfaces, but not all of them were changed (sorry, was in a hurry, just finished that a minute ago) etc etc. So there is still a lot of room to improve things.

Still, maybe the code will be of use for you.

Here it is:
https://github.com/mvmn/metadata-extractor/commit/3d9443b0e4928aa5793bcfce3884a8d4b99f3829

**Comment by drewnoakes** [comment]
Yes, that little TODO masks a deeper issue. Bounds checking requires knowing the bounds, which if you're processing a stream means reading to the end.

I think there's possibly a good middle ground here. When the length is known (for a file, which is a very common case) then use it. Otherwise fall back to scanning if needed.

Maybe we pass a `Long` in, which can be `null`, and use it when present, otherwise fall back to `reader.getLength()`.

**Comment by mvmn** [comment]
`I think there's possibly a good middle ground here. When the length is known (for a file, which is a very common case) then use it. Otherwise fall back to scanning if needed.

Maybe we pass a Long in, which can be null, and use it when present, otherwise fall back to reader.getLength().`

That's roughly what I did. Although I used long instead of Long, passing -1 will signify not known length.
Length is taken from a File. The only thing missing is actually using -1 when File cannot be deduced from URL, but that's a minor thing which I'm about to add.

The problem is though, passing that long parameter around requires lots of changes in API. Thus a huge diff, JavaDoc generation seems to be broken by added parameters etc.

**Comment by drewnoakes** [comment]
-1 seems like a fine choice too. I only skimmed your diff so apparently
missed that part, but will get down the code and try it out soon.

**Comment by drewnoakes** [comment]
`getLength` is only used in `TiffReader`.

Possibly easier to store the file length value in `RandomAccessReader` implementations, instead of passing it in every extractor method overload.

**Comment by drewnoakes** [comment]
Ok so looking a little deeper I found the actual problem.

The `RandomAccessReader` already caches the file's length, however `ImageMetadataReader` passes only an `InputStream` to it's inner-, type-specific readers. So that information was not included.

I've made a change that is narrower in scope than yours, but addresses the core issue of scanning to EOF for TIFF files, such as camera raw files. This gives a decent speed up on the raw files in the sample library, so thanks for bringing this to everyone's attention.

Please take a look at the commit and see if you think I missed anything.

Should get a new release out soon. It's overdue.

**Comment by drewnoakes** [comment]
This is available in 2.9.0.
