### ISSUE TITLE
Could UTF-8 decode be used instead of ASCII for Panasonic Makernote city etc?

### ISSUE THREAD

**Issue by daniel6651** [drewnoakes/metadata-extractor#191]
Hi

When I tried to use your excellent library on some photos from Denmark, I got strange location names with some special danish characters replaced by "??"

State = SJ??LLAND
Landmark = ODDEN FISKERI OG LYSTB??DEHAVN

In TagDescriptor.java - could UTF-8 be used instead of ASCII for the conversion in getAsciiStringFromBytes()?
Or is it not stored as UTF-8 in the original info?

BR

Daniel

**Comment by drewnoakes** [comment]
The .NET implementation stores strings as `byte[]` so that you as the user can always override the encoding.

https://github.com/drewnoakes/metadata-extractor-dotnet/pull/34

This behaviour has not yet been ported to this Java project. If you wanted to take a shot at submitting a PR I'd be happy to assist where needed.

**Comment by daniel6651** [comment]
Hi
I just submitted a pull request with a first try to get the same changes in for the Java version.Did also add a fix for PanasonicMakernotes that was also needed for my case.
BR
Daniel 

    Den tisdag, 16 augusti 2016 12:22 skrev Drew Noakes <notifications@github.com>:
 

 The .NET implementation stores strings as byte[] so that you as the user can always override the encoding.drewnoakes/metadata-extractor-dotnet#34This behaviour has not yet been ported to this Java project. If you wanted to take a shot at submitting a PR I'd be happy to assist where needed.—
