### ISSUE TITLE
Date date = directory.getDate(IptcDirectory.TAG_DATE_CREATED); //Wrong year and more

### ISSUE THREAD

**Issue by george84** [drewnoakes/metadata-extractor#212]
When doing `Date date = directory.getDate(IptcDirectory.TAG_DATE_CREATED);`

then I get for date: 

> Thu Jan 01 01:00:00 CET 20151007

a year of 20151007 is quite big, correct date as displayed in Adobe Acrobat would be

> 07.10.2015 07:45:07

It is unfortunate that new version of metadata-extractor is not compatible with previous version.

**Comment by kwhopper** [comment]
Do you have an example file?

**Comment by george84** [comment]
Yes, here it is

![2015_1007_074507aa](https://cloud.githubusercontent.com/assets/8818287/21340038/20c0df5c-c684-11e6-8bf7-cd5e78e6f316.jpg)

**Comment by drewnoakes** [comment]
Thanks for the sample image. Can you please also elaborate on which versions you're referring to?

**Comment by drewnoakes** [comment]
The issue here applies to any IPTC dates accessed via `Directory.getDate` it seems.

The problem is that IPTC stores dates as strings (eg: `"20151007"`), and the parsing logic in `Directory.getDate` treats this integer as a year.

A workaround is to use `getString` instead and parse it yourself. 

A fix will follow shortly.

**Comment by george84** [comment]
Thank you. My problem solved!
