### ISSUE TITLE
NegativeArraySizeException

### ISSUE THREAD

**Issue by imakhalova** [drewnoakes/metadata-extractor#272]
```
Fatal Exception: java.lang.NegativeArraySizeException: -2147475456
       at com.drew.lang.StreamReader.getBytes(SourceFile:61)
       at com.drew.imaging.png.PngChunkReader.extract(SourceFile:93)
       at com.drew.imaging.png.PngMetadataReader.readMetadata(SourceFile:81)
       at com.drew.imaging.ImageMetadataReader.readMetadata(SourceFile:126)
       at com.drew.imaging.ImageMetadataReader.readMetadata(SourceFile:162)
```

Looks like `reader.getInt32()` returns signed int...probably better to store it in long? Or handle somehow gracefully if it's negative.

**Comment by drewnoakes** [comment]
Can you attach an image that reproduces this please?

**Comment by imakhalova** [comment]
I have no images for repro, but I guess it's just really huge image

**Comment by drewnoakes** [comment]
I don't think it's a large image. That number looks familiar. My guess is
that it contains corrupted data, or something valid that we haven't tested
on before. Please try to get a repro image.

[via phone]

**Comment by drewnoakes** [comment]
Looking at this again it does seem that the data was invalid.

[From the spec](https://www.w3.org/TR/2003/REC-PNG-20031110/#5Chunk-layout):

> Length: A four-byte unsigned integer giving the number of bytes in the chunk's data field. The length counts only the data field, not itself, the chunk type, or the CRC. Zero is a valid length. Although encoders and decoders should treat the length as unsigned, its value shall not exceed 2^31-1 bytes.

So if the 4-byte length has the high bit set (making it negative if treated as signed) it _should_ be considered invalid. That still gives you 2GB+ to work with.

I'll add a better error message, and raise a `PngProcessingException` instead of a `NegativeArraySizeException`.
