### ISSUE TITLE
write to json format

### ISSUE THREAD

**Issue by kousuke** [drewnoakes/metadata-extractor#279]
Metadata-extractor is great to parse exif data. It's really easy to use.
so how can I write all exif data to somewhere as common format like json?

Thanks!
kousuke

**Comment by PaytonGarland** [comment]
I usually just use Gson for this.  If you want to just serialize the whole metadata/directory object, you will need to create an exclusion strategy because there are a couple fields that will cause a stack overflow.  This is a really simple example of that:
```
Gson gson = new GsonBuilder().setPrettyPrinting().setExclusionStrategies(new ExclusionStrategy() {
    @Override
    public boolean shouldSkipField(FieldAttributes f) {
        if (f.getDeclaredClass() == TagDescriptor.class)
            return true;
        if (f.getDeclaringClass() == Tag.class && f.getDeclaredClass() == Directory.class)
            return true;
        return false;
    }

    @Override
    public boolean shouldSkipClass(Class<?> aClass) {
        return false;
    }
}).create();
System.out.println(gson.toJson(metadata));
```
The defined tag list doesn't provide any useful information in this example, so you could also skip fields with a declared class of Collection.  This example will return an array of directories that have tag maps whose key is the id:
```
"_tagMap": {
        "16": "Clean7Bit",
        "3": "0 0 289 361",
        "19": "2",
        "5": "9/7/05",
        "6": "Adobe Illustrator(R) 12",
        "7": "Alan Lillich",
        "41": "29100 Hex Bytes",
        "11": "1",
        "14": "BlueSquare.eps"
     }
```

Another option would be to create your own object to serialize that formats the values a little better or put the results in another HashMap.  An example of that would be creating a new HashMap<String, String> that would store the tag name as a key and tag description as a value.  Then you could just serialize that.

**Comment by kousuke** [comment]
Great, thank you @PaytonGarland . It's really good to know. 
Do you have any plan to do this officially and having way to back to metadata from stored data?

**Comment by PaytonGarland** [comment]
@kousuke No problem.  I am not the owner of this library, so that would be a question for Drew.

As for converting the JSON back to a metadata object, I would imagine that's a little more difficult as we had to use the exclusion strategy in my first example.  Definitely able to be done one way or another, though.

**Comment by kwhopper** [comment]
There is a very similar debate about database serialization here #216. I think the same problems and issues would apply to json formats. In general, it's very difficult to serialize a library that changes all the time. Old serialized versions of the object tend to drift away quickly from compatibility with the current code.

**Comment by drewnoakes** [comment]
As discussed above, I don't think the serialisation of directories is something we want for this library. If it's difficult to write your own small to/from mapping code, then that's something we can fix, but supporting JSON, XML, Java serialisation, etc... doesn't feel like a good idea to me.

**Comment by drewnoakes** [comment]
I would be happy to include sample code for this on the wiki. @PaytonGarland, would you be able to create a short wiki page with your GSON code?
