### ISSUE TITLE
Library

### ISSUE THREAD

**Issue by Lambo11** [drewnoakes/metadata-extractor#377]
I have installed the metadata library (the Maven package into my project). But, when i want to import the library (eg import .com.drew.metadata) it appears to be an error. Can someone help me? I'm new to this.

**Comment by Lambo11** [comment]
![screenshot 43](https://user-images.githubusercontent.com/44737412/48690459-a01e4800-ec09-11e8-9a50-19679faec048.png)
I'm sorry for the undetailed information. Here is the screenshot of the coding

**Comment by Nadahar** [comment]
You must make sure that any library you want to use is on your classpath. Otherwise, importing them won't work. I don't know if you use Maven, but adding it as a dependency in `pom.xml` is usually enough. I you don't use a build system, you will have to manage JARs and the classpath manually.

**Comment by Lambo11** [comment]
![screenshot 44](https://user-images.githubusercontent.com/44737412/49055372-4bdf1d80-f232-11e8-8e8c-6ad33bf3d26d.png)

No, I don't use Maven and I never use it. Is it compulsory to use Maven? I use the usual Java class. And yes, I already add the metadata extractor library into my project as you can see in the screenshot.

**Comment by Nadahar** [comment]
You don't *have* to use Maven, it's just that I think most Java developers use Maven or Gradle. I don't know NetBeans and have no idea how classpaths are configured manually, but I'm pretty sure your problem is with the classpath. A screenshot of the JAR being added to `Libraries` doesn't tell me anything, since I don't know what NetBeans does with what's put there.

**Comment by payton** [comment]
Assuming this issue has been resolved. Feel free to re-open if necessary.
