### ISSUE TITLE
Review QuickTime matrix calculation

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#384]
QuickTime files use a 3x3 matrix to specify rotation/scaling/translation.

The .NET library received a port from the Java implementation, which was then fixed in https://github.com/drewnoakes/metadata-extractor-dotnet/pull/152.

We need the same change applied here.

**Comment by payton** [comment]
This data comes from the Track Header Atom (tkhd), which is not currently parsed in QuickTime files.

**Comment by gmanjon** [comment]
Hi Everyone! Greate tool. Really awsome.

If I'm not mistaken this issue has been fixed in this commit: 

https://github.com/drewnoakes/metadata-extractor/commit/40fd789c3076af09e1d22ccd7f6192d854850574

I was going to develop it because I needed this info but I found it on master. When are new versions released? Thank you

**Comment by drewnoakes** [comment]
@gmanjon thanks for following up, I'll close this issue.

We've had a few changes recently. I'll get a new release out shortly.
