### ISSUE TITLE
Date one hour off for some videos

### ISSUE THREAD

**Issue by davidekholm** [drewnoakes/metadata-extractor#408]
The following mp4 video is reported to have a creation time of 2018:06:10 19:36:49 according to exiftool, but Metadata-extractor reports 2018-06-10 20:36
Do you know why?

File: http://jalbum.net/download/20180610_153638.mp4

**Comment by EarlyOut** [comment]
I shot that video, on a Samsung Galaxy S7. The actual creation time was 2018-06-10 15:36, as the file name indicates. So it's not one hour off - it's a full five hours off.

**Comment by Nadahar** [comment]
My bet would be time-zones.

**Comment by EarlyOut** [comment]
Sounds right. File Explorer and Finder get it right, but only because I'm sitting here in UTC-5, exactly where the video was shot. A video from the same S7, but shot in the Engadine Valley (UTC+1), is off by six hours here. Window is showing me what time it was _here_ when the video was taken. Not very useful!

**Comment by Nadahar** [comment]
There's a general lack of strategy when it comes to time-zones, and it all depends on the implementation details. The de facto standard that has evolved is generally to store everything as UTC and then translate it to the local time-zone when displaying. This will be appropriate in many situations, but might not be what you want for a video or image.

The question is also what the camera/phone is storing. Is it actually storing the UTC timestamp, or is it simply storing the local device time (aka the time in the local time-zone). Since there's a general lack of ways to store this information, software might have to "guess". To figure this out properly, the standard for the format in question must be studied as to the rules for time-zones for the given format. Even if the standard clearly defines how this should be handled, implementations might not respect this.

**Comment by davidekholm** [comment]
Thanks for the breif on this. So what is the raw date related metadata looking like for this specific image is my question? What is desired is probably to display the time in local time.

**Comment by Nadahar** [comment]
I would think that what Metadata-extractor extracts is the "raw date". It is then up to the developer (that use Metadata-extractor) to convert it appropriately. To figure out what the "rules" are for a particular format, you'd have to look in the standard for said format.

**Comment by EarlyOut** [comment]
Someone please examine that "bear" video. The UTC, as correctly recorded in the video, is 19:36 (local time was 15:36 EDT). Is that what metadata-extractor yields? The indications are that it might be one hour off. Either that, or the application (jAlbum) is somehow creating the one-hour error (it's showing 20:36).

**Comment by davidekholm** [comment]
jAlbum simply uses this one-liner to extract the date+time from that mp4 video, and now it shows up as 20:36 even though exiftool shows 19:36 (which is preferred):
```
Directory dir;
if ((dir = metadata.getFirstDirectoryOfType(Mp4Directory.class)) != null) {
            return dir.getDate(Mp4Directory.TAG_CREATION_TIME);
        }
```

**Comment by Nadahar** [comment]
@davidekholm That might be the problem. I still don't know the exact details of this, since I haven't taken the time to find and read the standard for this format, but Metadata-extractor isn't an end-user application. It's a programming library, and as such it shouldn't try to make the extracted data "presentable" to the user. 

What it should do, is to extract the metadata in the way that is most predictable for the developers who use it. To me that means: don't manipulate the data, just extract raw values.

The responsibility to make said data presentable should be with the application that interfaces with the users, here jAlbum.

I'm still not sure if this is what Metadata-extractor actually does, but this is how I think it should work, and it would make a lot of sense to me if this is how it actually does work.

**Comment by davidekholm** [comment]
I agree with you on that point. My suspicion is however that there is an error in Metadata-extractor as even exiftool (with is a rather techy tool) displays the data correctly

**Comment by EarlyOut** [comment]
Back in my "coding for a living" days, we had an expression about writing utility programs that others would be using: Don't do me any "favors."

Surely, the person using this application will want it to convert the result to..... No, no he won't. :)

**Comment by Nadahar** [comment]
There's a very easy way to test if Metadata-extractor or Exiftool applies time-zone conversion: Analyze the file with both on a given computer, change the OS timezone (and reboot if necessary) and then analyze with both again. The reported time should *not* change when the OS timezone is changed.

**Comment by EarlyOut** [comment]
Just did that test. Fascinating results. I've got a video shot at 13:18 UTC, and exiftool consistenly reports that, no matter what time zone my OS is set to.

With metadata-extractor, it's clear that something is amiss. If I set to EDT (UTC-4), the time is shown as 14:18 EDT. If I set to PDT (UTC-7), it's shown as 14:18 PDT.  Neither is correct, of course.

But now the best of all. If I set the OS to HST (UTC-10), it's shown as 13:48 HST. Note that it's not 13:18 or 14:18, but halfway between them! Hawai'i does not observe daylight saving time, but neither does it include a 30-minute offset.

**Comment by Nadahar** [comment]
You confuse me slightly. Does your last section apply to Metadata-extractor or something else? Some timezones do have half an hour offset. According to Wikipedia, Hawaii had UTC−10:30 from 1900 until 1947, so if the date (year) is also wrong whenever the conversion is made, this could actually be a correct result. By that I mean that for dates from 1900 to 1947, UTC-10:30 still applies.

What I don't understand is why Metadata extractor would translate the time for HST, but not for EDT and PDT. That doesn't make any sense. When you say that Metadata-extractor reports `14:18 EDT` and `14:18 PDT`, I am skeptical. I wouldn't think Metadata-extractor reported a time-zone at all, in which case what it would be reporting is simply `14:18`. You would then interpret it as being EDT or PDT, but the actual time is just a "raw value" without a timezone.

There is a possible explanation that would explain all this except the Hawaii situation, and that is if the timezone in which the video was recorded was also stored in the metadata somewhere. If so, Exiftool might convert the "raw" value using said timezone before displaying. If so, jAlbum would be responsible for doing the same thing if it wanted to show the time the video was recorded in the local timezone where it was recorded.

**Comment by EarlyOut** [comment]
I can well understand your skepticism. If I weren't seeing it with my own eyes....

Here's the code I'm using to extract the metadata, code provide by Drew Noakes himself:

```
public static void saveMetadataToFile(File image, File output)

    throws ImageProcessingException, IOException
{
    Metadata metadata = ImageMetadataReader.readMetadata(image);
    PrintStream printStream = new PrintStream(output);
    try {
        for (Directory directory : metadata.getDirectories()) {
            for (Tag tag : directory.getTags()) {
                printStream.println(tag);
            }
        }
    } finally {
        printStream.close();
    }
}
```
And here's the output from my video, recorded at 13:18 UTC (09:18 EDT):

```
[MP4] Major Brand - MP4 v2 [ISO 14496-14]
[MP4] Minor Version - 0
[MP4] Compatible Brands - [MP4  Base Media v1 [IS0 14496-12:2003], MP4 v2 [ISO 14496-14]]
[MP4] Creation Time - Tue Jul 16 14:18:49 EDT 2019
[MP4] Modification Time - Tue Jul 16 14:18:49 EDT 2019
[MP4] Duration - 8164
[MP4] Media Time Scale - 1000
[MP4] Duration in Seconds - 00:00:09
[MP4] Transformation Matrix - 65536 0 0 0 65536 0 0 0 1073741824
[MP4] Preferred Rate - 1
[MP4] Preferred Volume - 1
[MP4] Next Track ID - 3
[MP4] Rotation - 0
[MP4 Video] Creation Time - Tue Jul 16 14:18:49 EDT 2019
[MP4 Video] Modification Time - Tue Jul 16 14:18:49 EDT 2019
[MP4 Video] ISO 639-2 Language Code - ```
[MP4 Video] Opcolor - 0 0 0
[MP4 Video] Graphics Mode - Copy
[MP4 Video] Compression Type - H.264
[MP4 Video] Width - 1920 pixels
[MP4 Video] Height - 1080 pixels
[MP4 Video] Depth - 24-bit color
[MP4 Video] Horizontal Resolution - 72
[MP4 Video] Vertical Resolution - 72
[MP4 Video] Frame Rate - 25.825
[MP4 Sound] Creation Time - Tue Jul 16 14:18:49 EDT 2019
[MP4 Sound] Modification Time - Tue Jul 16 14:18:49 EDT 2019
[MP4 Sound] ISO 639-2 Language Code - ```
[MP4 Sound] Balance - 0
[MP4 Sound] Format - MPEG-4, Advanced Audio Coding (AAC)
[MP4 Sound] Number of Channels - 2
[MP4 Sound] Sample Size - 16
[MP4 Sound] Sample Rate - 48000
[File Type] Detected File Type Name - MP4
[File Type] Detected File Type Long Name - MPEG-4 Part 14
[File Type] Detected MIME Type - video/mp4
[File Type] Expected File Name Extension - mp4
[File] File Name - 20190716_091839.mp4
[File] File Size - 17670607 bytes
[File] File Modified Date - Tue Jul 16 09:18:49 -04:00 2019
```

Take a look at those creation times. And switching time zones produces exactly the bizarre results I've posted above.

**Comment by Nadahar** [comment]
Ok, now I had to look :wink: 

There's definitely some very weird handling in Metadata-extractor, I'd go as far as to call it a bug. The following code converts the "raw" timestamps into Java `Date` instances: https://github.com/drewnoakes/metadata-extractor/blob/8352ce2bdfe559f0c2d28bd109e3a82af79abcbc/Source/com/drew/metadata/mp4/boxes/MovieHeaderBox.java#L79-L85

I'm not sure how the time base/epoch is defined for MP4 metadata, but it seems to me like the attempt to convert this into Java's time base/epoch (January 1, 1970, 00:00:00 GMT) is flawed. It could be that I misread the code, but setting epoch to that for Apple seems weird. Defining the year to 1904 also explains why Hawaii has -10:30 time zone...

**Comment by drewnoakes** [comment]
Tagging @payton who contributed this code. Payton, do you remember why the date processing was done this way?

**Comment by Nadahar** [comment]
Looking up page 23 in `ISO/IEC 14496-12:2015` shows:
* `creation_time` is an integer that declares the creation time of the presentation (in seconds since midnight, Jan. 1, 1904, in UTC time) 
* `modification_time` is an integer that declares the most recent time the presentation was modified (in seconds since midnight, Jan. 1, 1904, in UTC time)

This explains the strange Epoch. Something goes wrong though, it seems to me like timezone is "kept out of the loop" which probably leads to Java applying the "default timezone" retrieved from the current OS settings at some point, which causes trouble.

**Comment by Nadahar** [comment]
It seems like the fix is quite simple, the problem seems to be `Calendar.getInstance()` which is used as the "base instance" before the Epoch time is set. The JavaDoc for `getInstance()` states:
> Gets a calendar using the default time zone and locale. The
> `Calendar` returned is based on the current time
> in the default time zone with the default
> `FORMAT` locale.

That means that the instance will use the default (OS) timezone and the default (OS) locale. My suggested fix in #410 doesn't address the locale issue, but sets the timezone to `UTC` as defined in `ISO/IEC 14496-12:2015`.

I simply assumed that the same is true for the other places in the code with the same date parsing, so I changed them as well. I haven't verified if the assumption is true.

**Comment by drewnoakes** [comment]
I commented on #410 with a suggestion to fix the locale issue.

**Comment by drewnoakes** [comment]
With @Nadahar's changes from #410, I now see:

```text
[MP4 Sound] Creation Time = Mon Jun 11 05:36:49 +10:00 2018
[MP4 Sound] Modification Time = Mon Jun 11 05:36:49 +10:00 2018
```

Note that I'm in Melbourne, Australia, which is GMT+10, which I believe fits with the above information.
