### ISSUE TITLE
Add module-info for java9+

### ISSUE THREAD

**Issue by lanthale** [drewnoakes/metadata-extractor#566]
Please can you add a module-info so that the lib is also usable with java 9+ ? If it needs to be compatible with java 8 than a multi-release lib would be an option.

**Comment by drewnoakes** [comment]
How is the library not usable with Java 9+?

Can you, or someone else, provide some more guidance here please?

**Comment by lanthale** [comment]
It is usable on the classpath. But if you use the modulepath than you need in your lib a file “module-info” where you express which classes are exposed to the other modules. 

Adding this during compile time is easy. Addi g afterwards is difficult because you must than use a tool such as moditect. And you can add it in a way that java 8 is not influenced during build. 

Is java 8 a requirement ?

If you need I can create a pull request with the module-info and the changed pom.xml ?

**Comment by berndmichaely** [comment]
Unfortunately, there is a bit more involved into making the library modular than just adding a module-info.java file…

First of all, it is desirable to have a modular library for reasons, including:

- Java9+ has its runtime library modularized, which (optionally) offers the ability to deploy only the JRE modules the application needs, thereby reducing the size of the resulting output
- modules can not overlap in packages, which results in a speed advantage in class localization and loading

For this to work, it is necessary to use explicit modules only, that is modules, which explicitly declare their own requirements in a module descriptor (a module-info.class file).

Otherwise, if automatic ('just' named) modules or the unnamed module (containing the classpath) are involved, the compiler can not automatically deduce the needed modules. In this case, there will be an implicit dependency to the `java.se` aggregator module which contains the whole JavaSE.

Note, that _all_ modules must have module descriptors, including third party dependencies, e.g. in this case the xmpcore lib (which is not modularized, I think? If so, one would need to provide a modularized version of this lib, too…).

**Comment by lanthale** [comment]
To modularize the dependencies it is possible to use moditect. But you are right that the change is bigger than someone thinks of and means that the lib cannot be compiled longer with java8. I do not know if that is a problem.

**Comment by drewnoakes** [comment]
Thank you all for your input here. There seem to be two barriers to this:

1. Adobe's `xmp-core` library must be made modular in this way
2. Java 8 support must be dropped

Packaging Adobe's package ourselves seems like not such a great idea.

We currently support Java 1.6 IIRC.

How are modules packaged and deployed? Does this still use Maven tooling and hosting?

**Comment by Nadahar** [comment]
Dropping Java 8 support is very premature in my opinion. There are still lots of things that have no replacement after Java 9 was "nerfed", so I would expect that a lot of software will have to stay with Java 8 for years to come. Have libraries started to ditch Java 8 support? It's OK for an application to do it if it doesn't need any of the things that were removed, but libraries would narrow which projects that could use them considerably.

If all this achieves is to save some space for the runtime, it's hard for me to understand how it could be something to consider at all. I get that embedded systems might benefit substantially, but a Java installation isn't really a considerable "burden" on a computer these days.

**Comment by berndmichaely** [comment]
Indeed (and correct me, if I'm wrong) it basically remains as a problem to the end user to use third party modules as explicit modules, if desired. To compile the metadata library itself as a module, it should be sufficient to load the xmp-core module as automatic module through the module path (not the class path), with `requires xmpcore` added to the module-info.

**Comment by Nadahar** [comment]
@drewnoakes I've not done much development the last year due to health issues, so I don't feel very "up to date". I also still stick with Java 8 because of all the limitations introduced in Java 9 - so I have no experience with modules either. All I understand is that it's a problem for those that use modules when one of their dependencies don't have a module declaration. But, as far as I can remember, you can't build JARs that's compatible with earlier versions of Java while also including the module information, at least not without "cheating" like they do [here](https://aseovic.medium.com/building-java-8-compatible-modular-jars-715b04299a7c).

Isn't that the crux of the problem - the fact that even though you can make the Maven build file build versions both for Java 9+ and for prior versions, it will generate different JARs and you can't have one that does both? That means, as far as I can understand, that you have to "choose" which version to publish with Maven, and there's no way to include "module support" in the published JAR without also breaking backwards compatibility (except by "cheating" as described above where you generate the modules file with Java 9 and then overwrite the compiled classes with their Java 8 versions).

I my assumption that you can't have one JAR support modules _and_ work with earlier versions is wrong, then it all comes down to what is the best way to support modules - and there I have no clue.

@tsmock's post above seems to indicate that there's a way to achieve both - which would be great.
