### ISSUE TITLE
Improve Olympus makernote support

### ISSUE THREAD

**Issue by drewnoakes** [drewnoakes/metadata-extractor#93]
There are several more tags here:

http://www.exiv2.org/tags-olympus.html

And plenty of unknown tags in the image database, such as:

``` plain
[Olympus Makernote - 0x0300] Unknown tag (0x0300) = 0
[Olympus Makernote - 0x0301] Unknown tag (0x0301) = 0
[Olympus Makernote - 0x0302] Unknown tag (0x0302) = 0
[Olympus Makernote - 0x0303] Unknown tag (0x0303) = 0
[Olympus Makernote - 0x0304] Unknown tag (0x0304) = 0
[Olympus Makernote - 0x0306] Unknown tag (0x0306) = 0
[Olympus Makernote - 0x0f00] Data Dump = [1502 bytes]
[Olympus Makernote - 0x0400] Unknown tag (0x0400) = 1
[Olympus Makernote - 0x0401] Unknown tag (0x0401) = 2
[Olympus Makernote - 0x0402] Unknown tag (0x0402) = 16814089
[Olympus Makernote - 0x0403] Unknown tag (0x0403) = 1
[Olympus Makernote - 0x0404] Unknown tag (0x0404) = 000J76206192
[Olympus Makernote - 0x0405] Unknown tag (0x0405) = e72
[Olympus Makernote - 0x0225] Unknown tag (0x0225) = 00
```

**Comment by drewnoakes** [comment]
This covers all the top-level tags, however there are still several sub-directories of data. One is already covered (camera settings), but exiv2.org shows several more to add.

This is a good issue for someone new to the project to pick up.

**Comment by geekysquirrel** [comment]
When trying to use the OlympusMakernoteDirectory for photos taken with my E-510, I always get "Illegally sized directory" with no tags contained.
According to <a href="http://owl.phy.queensu.ca/~phil/exiftool/makernote_types.html">exiftool</a>, my camera has a different Makernote directory (Olympus2 rather than Olympus), so metadata-extractor cannot read it.
I'm not sure what the correct way of fixing this would be: extend the existing directory class or create a new one?

Here's a sample photo (cloning a 3GB repo takes a long time with my connection)
![olympus e-510](https://cloud.githubusercontent.com/assets/6008491/10765999/580a266e-7ccd-11e5-8320-12919b04e518.jpg)

**Comment by drewnoakes** [comment]
I noticed that the illegally sized Olympus makernote directories claim to have 18671 entries. This number is `0x4949` in hex, or `"II"` in ASCII. TIFF data uses `II` to indicate Intel byte ordering. Perhaps, as @geekysquirrel says, there's a different format for certain Olympus makernotes.

**Comment by drewnoakes** [comment]
Exiv2.org says there are two different Olympus makernote preambles, with different offsets. This explains the extra bytes.

> `"OLYMP\0"` with IFD at offset 8
> `"OLYMPUS\0II"` with IFD at offset 12, and makernote offsets relative to the beginning of the makernote

http://exiv2.org/makernote.html

**Comment by drewnoakes** [comment]
@kwhopper has done a tonne of good work here on the .NET version which is pending porting to Java:

- Raw Development (drewnoakes/metadata-extractor-dotnet#44)
- Raw Development 2 (drewnoakes/metadata-extractor-dotnet#45)
- Image Processing (drewnoakes/metadata-extractor-dotnet#46)
- Focus Info (drewnoakes/metadata-extractor-dotnet#47)

Addresses "Invalid TIFF tag format code 13 for tag 0x20*0" issues.
